In [1]:
import numpy as np

## Declaring scalars, vectors, and matrices

In [4]:
scalar = np.array(5)
vector = np.array([3,-2,7])
matrix = np.array([[3,2],[-1,9],[4,5]])

In [5]:
print(scalar.shape, vector.shape, matrix.shape)

() (3,) (3, 2)


In [6]:
matrix_reshaped = matrix.reshape(2,3)
matrix_reshaped

array([[ 3,  2, -1],
       [ 9,  4,  5]])

In [8]:
vector_shaped = vector.reshape(-1,1)
vector_shaped.shape

(3, 1)

## Declaring a tensor

In [10]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [11]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [13]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [14]:
t.shape

(2, 2, 3)

## Addition/Subtraction

In [15]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

In [16]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

The exception to always needing same dimensions is adding a scalar

In [17]:
m1 + 2

array([[ 7, 14,  8],
       [-1,  2, 16]])

## Transposing

In [18]:
m1_transposed = m1.T
m1_transposed

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

## Multiplication

#### Vector dot product 

In [20]:
v1 = np.array([2,3,4])
v2 = np.array([4,5,6])
np.dot(v1,v2) # scalar product!

47

In [21]:
# dot product = sum of paired multiples
2*4 + 3*5 + 4*6

47

#### Vector * vector

In [22]:
v1*v2 # vector product!

array([ 8, 15, 24])

#### Scalar * Matrix

In [23]:
m1*4 # Keeps same shape

array([[ 20,  48,  24],
       [-12,   0,  56]])

#### Matrix dot product

In [25]:
# Doesn't work - Length of 2nd dimension of first matrix must equal length of 1st dimension of second matrix!
np.dot(m1,m2)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

Let's re-use the transposed matrix from earlier

In [27]:
m1_transposed

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In [28]:
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

Then see what the dot product turns out like, **the output will have the row count of the first matrix, and the column count of the second matrix**

In [36]:
np.dot(m2, m1_transposed) # 2x3 matrix dot 3x2 matrix = 2x2 output matrix

array([[183,  71],
       [ 11, -73]])

This works by multiplying **the individual row and column vectors respectively** - the reason for needing the same column/row count respectively is because with vector multiplication both must be **the same length**.

The first value in the top left is the vector dot product of the **first row of the first matrix** and the **first column of the second matrix**, and so on.

In [39]:
r1c1 = np.dot(m2[0,:],m1_transposed[:,0])
r1c2 = np.dot(m2[0,:],m1_transposed[:,1])
r2c1 = np.dot(m2[1,:],m1_transposed[:,0])
r2c2 = np.dot(m2[1,:],m1_transposed[:,1])
output = np.array([[r1c1,r1c2],[r2c1,r2c2]])
output

array([[183,  71],
       [ 11, -73]])