In [2]:
import numpy as np

## Create board

In [119]:
board_init = np.zeros(shape=(9,9),dtype=int)

In [120]:
board_init.shape

(9, 9)

In [121]:
print(board_init)

[[0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]]


## Add numbers

In [176]:
board_init[0,:] = [0,0,0,0,0,0,5,7,3]
board_init[1,:] = [8,0,0,0,2,0,0,0,0]
board_init[2,:] = [7,0,0,9,0,0,8,1,0]
board_init[3,:] = [5,8,0,7,0,6,0,0,0]
board_init[4,:] = [0,0,1,8,0,0,0,6,0]
board_init[5,:] = [2,3,0,0,4,0,0,0,9]
board_init[6,:] = [9,1,5,0,0,0,0,0,0]
board_init[7,:] = [0,0,0,0,8,0,6,0,1]
board_init[8,:] = [0,0,0,0,0,0,0,4,0]

In [178]:
print(board_init)

[[0 0 0 0 0 0 5 7 3]
 [8 0 0 0 2 0 0 0 0]
 [7 0 0 9 0 0 8 1 0]
 [5 8 0 7 0 6 0 0 0]
 [0 0 1 8 0 0 0 6 0]
 [2 3 0 0 4 0 0 0 9]
 [9 1 5 0 0 0 0 0 0]
 [0 0 0 0 8 0 6 0 1]
 [0 0 0 0 0 0 0 4 0]]


## Create functions

Checking columns & rows for unique values is simple in arrays, but checking boxes is slightly trickier - as you need to check an array where all values have the same multiple of 3 row/column group.

eg. the value at row 2, column 3 is in the first group of 3 of both rows and columns. To figure these groups out we need to be able to round up to the nearest 3 for each index to identify these groups

In [179]:
def roundup_to_nearest_three(index):
    roundup_float = np.ceil((index + 1) / 3) * 3 # Add 1 as indices start from 0
    roundup_int = np.int(roundup_float)
    
    return roundup_int

Using the above we need to be able to check the unique values for row/column/box for a given pair of indices

In [180]:
def check_unique(board, row, column):
    # Get distinct values from row and column
    row_values = np.unique(board[row,:])
    col_values = np.unique(board[:,column])
    
    # First define the box that the row/column falls into
    # This will be a group of 3 in each axis
    row_grp = roundup_to_nearest_three(row)
    col_grp = roundup_to_nearest_three(column)
    
    # Then get distinct values from boxes
    box_values = np.unique(board[row_grp-3:row_grp, col_grp-3:col_grp])
    
    # Bring all into one list
    all_values = np.concatenate((row_values, col_values, box_values), axis=None)
    
    # Then take the unique values from all of them
    unique_values = np.unique(all_values)
    
    return unique_values

Finally, if the above function means only 1 number can occupy the value of a cell - then overwrite it!

In [181]:
def fill_values(board, row, column):
    # We're only interested in values not yet filled
    if board[row,column] == 0:
        existing_values = check_unique(board, row, column)
        potential_values = [value for value in range(1,10) if value not in existing_values]
        
        # If there's only one potential solution, overwrite zero with that value
        if len(potential_values) == 1:
            board_play[row,column] = potential_values[0]
            print('Row: ', str(row + 1), '& Col: ', str(column + 1), ' overwritten with ', str(potential_values[0]))

## Play!

In [182]:
board_play = board_init.copy()

# Restrict to max of 10 loops
for i in range(10):
    
    # Loop through table columns & rows
    for row in range(9):
        for column in range(9):
            fill_values(board_play, row, column)
                
    print('\n Loop number ', str(i + 1), ' complete \n')
    
    # Checks array for number of non-filled values remaining
    zeroes_remaining = np.count_nonzero(board_play == 0)
    
    if zeroes_remaining == 0:
        print('Finished!')
        break
    else:
        print(str(zeroes_remaining), ' zeroes left')

print(board_play)

Row:  2 & Col:  8  overwritten with  9
Row:  5 & Col:  1  overwritten with  4
Row:  8 & Col:  1  overwritten with  3
Row:  9 & Col:  1  overwritten with  6

 Loop number  1  complete 

50  zeroes left
Row:  1 & Col:  1  overwritten with  1
Row:  1 & Col:  5  overwritten with  6
Row:  2 & Col:  7  overwritten with  4
Row:  2 & Col:  9  overwritten with  6
Row:  3 & Col:  9  overwritten with  2
Row:  4 & Col:  3  overwritten with  9
Row:  4 & Col:  9  overwritten with  4
Row:  5 & Col:  2  overwritten with  7
Row:  5 & Col:  9  overwritten with  5
Row:  6 & Col:  3  overwritten with  6
Row:  6 & Col:  8  overwritten with  8
Row:  9 & Col:  2  overwritten with  2

 Loop number  2  complete 

38  zeroes left
Row:  1 & Col:  4  overwritten with  4
Row:  1 & Col:  6  overwritten with  8
Row:  2 & Col:  2  overwritten with  5
Row:  2 & Col:  3  overwritten with  3
Row:  2 & Col:  4  overwritten with  1
Row:  2 & Col:  6  overwritten with  7
Row:  3 & Col:  3  overwritten with  4
Row:  6 & Col